radar:
    device: AWR1843
    port: null # auto-detect
    frequency: 77.0
    idle_time: 5.0
    adc_start_time: 5.7
    ramp_end_time: 59.00
    tx_start_time: 1.0
    freq_slope: 67.012
    adc_samples: 256
    sample_rate: 5000
    frame_length: 64
    frame_period: 50.0
capture:
    sys_ip: 192.168.33.30
    fpga_ip: 192.168.33.180
    socket_buffer: 6291456